### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by zettam** [kauegimenes/plague-api#1]
Can't seem to make this work.
Unexpected tokens, or undefined's.

**Comment by kaue** [comment]
I will check this later, maybe the plague api changed.

**Comment by zettam** [comment]
Thank you

**Comment by kaue** [comment]
This should fix the problem, please give a try with this minor change https://github.com/kauegimenes/plague-api/commit/0e6d1bc13b335deba0669f93ac1184ae018dab8c

**Comment by zettam** [comment]
Thank you! Works.
Will you update the npm package?
Cheers

**Comment by kaue** [comment]
@zettam Yeah, i will do that tomorrow.

**Comment by zettam** [comment]
Thank you :+1:

**Comment by kaue** [comment]
@zettam Done, this fix is included in v1.0.5
