### ISSUE TITLE
Not possible to change location

### ISSUE THREAD

**Issue by zettam** [kauegimenes/plague-api#2]
I've been trying to set location for cards using .set({lat,long}). The created cards, for some reason, always have Montreal, Canada as the location attached to them; but interestingly the map location being displayed changes (to the actual lat/long I set).

I'm wondering if this is a bug of the api - or if this is something else that can be solved?

Also, I was unable to find any information about the actual api on plague website; how/where did you obtain the information to create the api for the app?

Thank you very much!

**Comment by borazslo** [comment]
In the plague api the actual coordinates and the label for these coordinates are two different things. On the Line118 and Line141 you see how the label for the coordinates are sent through "meta" tag.  These line should be changed.

**Comment by kaue** [comment]
@zettam I will include a .set parameter tof change the metatag, this will work for you?

**Comment by zettam** [comment]
I already changed the api to test, however it would be an amazing addition :+1: 
Also, now I'm wondering if the "closest n people" algorithm works with true latitude and longitude, or works with custom metatags? I set my location as "Sun" now; do you know if this is anyhow "breaking the rules"?

**Comment by kaue** [comment]
@zettam @borazslo This enhancament is avaliable in v1.0.6 

``` javascript
var plague = require('plague-api').set({
  latitude: -99.999999999999,
  longitude: -99.999999999999,
  administrativeArea: 'Quebec',
  country: 'Canada',
  locality: 'Montreal'
});
```

**Comment by kaue** [comment]
@zettam About your question, i belive the algorithm works with latitude and longitude only. And i dont know about the rules =(

**Comment by zettam** [comment]
thank you very much

**Comment by kaue** [comment]
@zettam =)
